site_name: HHU BlackAnt
site_author: 'HHU 机器人协会'
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
plugins:
  - search
theme:
  name: 'material'
  custom_dir: overrides
  language: 'zh'
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
copyright: |
  &copy; 2024 <a href="https://github.com/HHU-BlackAnt target = "_blank" rel = "noopener">HHU 机器人协会</a>

nav:
  - Home: index.md
  - 关于我们: about.md
  - 课程: 
    - 校内课程: course.md
    - 外部课程: course_external.md
  - 就业: job.md
  - 科研: 
    - 总纲: research.md
    - 机器人科研项目: project/robotics.md
    - 人工智能科研项目: project/ai.md